### ISSUE TITLE
Serve website from (and redirect to) https://[www.]sensorfu.com/

### ISSUE THREAD

**Issue by midael** [sensorfu/sensorfu.github.io#19]
URL: https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

"Beginning in July 2018 with the release of Chrome 68, Chrome will mark all HTTP sites as “not secure”."

I suspect that if we don't do the switch to everything over https://, it will eventually impact our search ratings as well. In addition, Firefox already shows http connections as non-secure (but doesn't rub it to users face).

**Comment by eemil** [comment]
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by ikisusi** [comment]
@nkapu you have been netflify'ing other site, maybe you could do the honors here as well?

**Comment by oherrala** [comment]
Do nothing and the issue resolves itself.

https://www.sensorfu.com/

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
