### ISSUE TITLE
Sharing in social media onerous => No graphics show up when sharing link to website

### ISSUE THREAD

**Issue by midael** [sensorfu/sensorfu.github.io#43]

**Comment by midael** [comment]
![fbpost](https://user-images.githubusercontent.com/7575408/52071691-55d61300-2538-11e9-8543-36ebf0740fe6.png)

E.g. this is how it shows up on FB

**Comment by midael** [comment]
Something like this ought to fix this: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by oherrala** [comment]
Some Open Graph tags added in #44. Facebook debugger looked good now. I consider this fixed.
