### ISSUE TITLE
Introduce beacon

### ISSUE THREAD

**Issue by nkapu** [sensorfu/sensorfu.github.io#5]
Deadline 2017-03-27

**Comment by evilon** [comment]
Beacon animation + sentence in the spirit of Mr. Larsson.

**Comment by evilon** [comment]
http://www.sensorfu.com/beacon.gif

**Comment by evilon** [comment]
"Mikko’s beacon will help him to seal his sandbox." won. 

Blog:

https://medium.com/scanabc/sensorfu-product-episode-02-a81b9a878d3f
